graph LR;
    qemu_drive_opts[QemuOptsList qemu_drive_opts]
        qemu_drive_opts --> disk1[QemuOpts disk1]
            disk1 --> option1a[QemuOpt: file=disk.raw]
            disk1 --> option1b[QemuOpt: format=raw]
            disk1 --> option1c[QemuOpt: if=ide]
        qemu_drive_opts --> disk2[QemuOpts disk2]
            disk2 --> option2a[QemuOpt: file=disk.qcow2]
            disk2 --> option2b[QemuOpt: format=qcow2]
            disk2 --> option2c[QemuOpt: if=virtio]
    qemu_machine_opts[QemuOptsList qemu_machine_opts]
        qemu_machine_opts --> singleton_machine["QemuOpts (singleton)"]
            singleton_machine --> option3a[QemuOpt: usb=on]
            singleton_machine --> option3b[QemuOpt: accel=kvm]
